server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://101.133.238.85:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mall
    password: Qq111111

#mybatis:
  #mapper-locations:
    #- classpath: mapper/*.xml
    #- classpath*: com/**/mapper/*.xml

